import type { Metadata } from 'next'
import React from 'react'
import StyledComponentsRegistry from '@/lib/StyledComponentsRegistry'
import './reset.css'

export const fonts = {
  family: 'Roboto',
  styles: 'wght@400;500;600;700;800;900',
  display: 'swap',
}
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fonts.family}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
